name: Docker build and Nomad deployment.
on:
  pull_request:
    branches:
      - main

env:
  NOMAD_URL: "http://142.93.129.1:4646"

jobs:
  build:
    name: Docker image builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Browse dirs.
        run: |
          ls -la

      - name: Get completed tasks from nomad job.
        id: complete1
        run: |
          curl  -H 'Content-Type: application/json' \
                                  --header "Authorization: Bearer ${{ secrets.NOMAD_TOKEN }}" \
                                  ${{ env.NOMAD_URL }}/v1/jobs\?prefix\=turisapps-web-1 

      - name: Get completed tasks from nomad job.
        id: complete
        run: |
          export complete=$(curl  -H 'Content-Type: application/json' \
                                  --header "Authorization: Bearer ${{ secrets.NOMAD_TOKEN }}" \
                                  ${{ env.NOMAD_URL }}/v1/jobs\?prefix\=turisapps-web-1 \
                                  | jq -r '.[0].JobSummary.Summary."turisapps-web-1".Complete' )
          echo "COMPLETE=$complete" >> $GITHUB_OUTPUT

      - name: python
        run: |
          echo ${{ steps.complete.outputs.COMPLETE }}
          export NOMAD_TOKEN=${{ secrets.NOMAD_TOKEN }}
          python3 .github/workflows/script.py
      
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: all
      - name: cat
        run: | 
          cat .github/workflows/script.py
