name: Docker build and Nomad deployment.
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Docker image builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Browse dirs.
        run: |
          ls -la
      
      - name: python
        run: |
          NOMAD_TOKEN=12345
          python3 script.py
